[build]
  command = "npm install" # Adjust according to your project setup
  publish = "public" # Your actual build output directory

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"
